branch-defaults:
  master:
    environment: aequitas-pro
environment-defaults:
  aequitas-pro:
    branch: null
    repository: null
global:
  application_name: aequitas
  branch: null
  default_ec2_keyname: aequitas
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: dsapp-ddj
  repository: null
  sc: git
  workspace_type: Application
