# Thresholds for positive class (absolutes top k and top k %)
score_thresholds:
    rank_abs: [150, 300]
    rank_pct: [1, 2, 5, 10]

#available options: "predefined", "majority" and "min_metric"
ref_groups_method: "predefined"

# if "predefined" is selected, you need to provide the column:value pairs to be used as reference
ref_groups:
  "attribute_1": "<0.30"

# fairness threshold to be used for assessing fairness
fairness_threshold: 0.8

# available fairness_measeure "Impact Parity", "Statistical Parity", "FPR Parity", "FDR Parity", "FNR Parity", "FOR Parity"
fairness_measures: ["FPR Parity", "FNR Parity"]
